// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKsrpG8f36fvPMj-P0ZMYqHc0nB1ffw30',
    appId: '1:909122665792:web:4d4de7be24da44048ccea5',
    messagingSenderId: '909122665792',
    projectId: 'flutter-firebase-dersler-9bd78',
    authDomain: 'flutter-firebase-dersler-9bd78.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-9bd78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhvkf95MAfPriMzrLYdzztF_PA7kJxzo',
    appId: '1:909122665792:android:82a661fae675d5e38ccea5',
    messagingSenderId: '909122665792',
    projectId: 'flutter-firebase-dersler-9bd78',
    storageBucket: 'flutter-firebase-dersler-9bd78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHu4R7bXKThEfV7amMVT_Kc9Js0qICqo',
    appId: '1:909122665792:ios:745f222d31e74ebc8ccea5',
    messagingSenderId: '909122665792',
    projectId: 'flutter-firebase-dersler-9bd78',
    storageBucket: 'flutter-firebase-dersler-9bd78.appspot.com',
    iosClientId: '909122665792-an0t7vpq21orub5o592aqpn5jrb7h4if.apps.googleusercontent.com',
    iosBundleId: 'Halil.com.flutter',
  );
}
